### ISSUE TITLE
After merging #15 site broken (in chrome 47.0)

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/scribus-tutorials#16]
![screenshot 2015-12-07 18 47 10](https://cloud.githubusercontent.com/assets/4140247/11644646/722d8156-9d13-11e5-97c9-3379203c892f.png)

**Comment by OceanWolf** [comment]
Ho hum, glad I just noticed this...  please mention me (I disabled the auto-emails unless mentioned because of matplotlib, where I could get 100 emails a day on various issues).

**Comment by OceanWolf** [comment]
It looks to me like a javascript error... can you open the javascript console?  Ctrl+Shift+J (Cmd+Option+J on Mac), and look for errors?

I don't think the error came from this update... no reason why, perhaps my previous one.  Did it give you a page not found error?

**Comment by luzpaz** [comment]
`reader.js:26 Uncaught SyntaxError: Unexpected token =`

**Comment by OceanWolf** [comment]
Ahh, that explains it... twas #11 that broke it...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by luzpaz** [comment]
confirmed fix :+1:
